export const GRAPHILE_WORKER_OPTIONS = Symbol('GRAPHILE_WORKER_OPTIONS');
export const GRAPHILE_TASK_NAME = Symbol('GRAPHILE_TASK_NAME');
export const GRAPHILE_TASK_OPTIONS = Symbol('GRAPHILE_TASK_OPTIONS');
export const JOB_PAYLOAD_INDEX = Symbol('JOB_PAYLOAD_INDEX');
export const JOB_HELPERS_INDEX = Symbol('JOB_HELPERS_INDEX');
