name: zod Package CI

on:
  pull_request:
    paths:
      - packages/zod/**
      - .github/workflows/zod.ci.yaml
      - .github/workflows/-template-package.ci.yaml
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  call-package-ci:
    name: Run CI for zod
    uses: ./.github/workflows/-template-package.ci.yaml
    with:
      package_name: zod
      package_npm_workspace: "@proventuslabs/nestjs-zod"
